# Generated by Django 4.0.10 on 2023-11-03 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('elemento', models.CharField(blank=True, max_length=255, null=True)),
                ('requisitos', models.TextField()),
                ('instrucciones', models.TextField()),
                ('tipo_item', models.CharField(choices=[('ataque', 'Ataque'), ('defensa', 'Defensa'), ('forjable', 'Forjable')], default='ataque', max_length=255)),
                ('tipo_arma', models.CharField(choices=[('ninguno', 'Ninguno'), ('espada_larga', 'Espada Larga'), ('espada_corta', 'Espada Corta'), ('baston', 'Baston')], default='espada_larga', max_length=100)),
                ('juego', models.CharField(choices=[('golden_sun', 'Golden Sun I'), ('golden_sun_2', 'Golden sun II')], default='golden_sun', max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
