# Generated by Django 4.0.10 on 2023-12-09 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('elemento', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Venus', 'Venus'), ('Marte', 'Marte'), ('Jupiter', 'Jupiter'), ('Mercurio', 'Mercurio')], max_length=255)),
                ('requisitos', models.TextField()),
                ('instrucciones', models.TextField()),
                ('tipo_item', models.CharField(choices=[('ataque', 'Ataque'), ('defensa', 'Defensa'), ('forjable', 'Forjable')], default='ataque', max_length=255)),
                ('tipo_arma', models.CharField(choices=[('ninguno', 'Ninguno'), ('espada_larga', 'Espada Larga'), ('espada_corta', 'Espada Corta'), ('baston', 'Baston')], default='espada_larga', max_length=255)),
                ('juego', models.CharField(choices=[('golden_sun', 'Golden Sun I'), ('golden_sun_2', 'Golden sun II')], default='golden_sun', max_length=255)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
