# Generated by Django 4.0.10 on 2023-11-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo',
            name='juego',
            field=models.CharField(choices=[('golden_sun', 'Golden Sun I'), ('golden_sun_2', 'Golden sun II')], default='golden_sun', max_length=255),
        ),
        migrations.AlterField(
            model_name='metodo',
            name='tipo_arma',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('espada_larga', 'Espada Larga'), ('espada_corta', 'Espada Corta'), ('baston', 'Baston')], default='espada_larga', max_length=255),
        ),
    ]
