# Generated by Django 4.0.10 on 2023-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro',
            name='elementos_filtro',
            field=models.CharField(default='', max_length=255),
        ),
    ]
