# Generated by Django 4.0.10 on 2023-11-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0002_filtro_elementos_filtro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtro',
            name='slug',
        ),
    ]
