# Generated by Django 4.0.10 on 2023-11-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopers',
            name='edad',
        ),
    ]
